// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressAutocompleteController from "./address_autocomplete_controller.js"
application.register("address-autocomplete", AddressAutocompleteController)

import AdminModalController from "./admin_modal_controller.js"
application.register("admin-modal", AdminModalController)

import BillingAddressAppearController from "./billing_address_appear_controller.js"
application.register("billing-address-appear", BillingAddressAppearController)

import ChangeNavbarBackgroundController from "./change_navbar_background_controller.js"
application.register("change-navbar-background", ChangeNavbarBackgroundController)

import CloseFlashController from "./close_flash_controller.js"
application.register("close-flash", CloseFlashController)

import DisapearFooterController from "./disapear_footer_controller.js"
application.register("disapear-footer", DisapearFooterController)

import DisapearNavbarController from "./disapear_navbar_controller.js"
application.register("disapear-navbar", DisapearNavbarController)

import FileUploadController from "./file_upload_controller.js"
application.register("file-upload", FileUploadController)

import FooterResponsivityController from "./footer_responsivity_controller.js"
application.register("footer-responsivity", FooterResponsivityController)

import GenerateBackgroundController from "./generate_background_controller.js"
application.register("generate-background", GenerateBackgroundController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import NavbarResponsivityController from "./navbar_responsivity_controller.js"
application.register("navbar-responsivity", NavbarResponsivityController)

import PaintingZoomController from "./painting_zoom_controller.js"
application.register("painting-zoom", PaintingZoomController)

import UserAddressAutocompleteController from "./user_address_autocomplete_controller.js"
application.register("user-address-autocomplete", UserAddressAutocompleteController)

import UserDropdownController from "./user_dropdown_controller.js"
application.register("user-dropdown", UserDropdownController)
